#!/usr/bin/python2
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Mar 27 21:30:12 2012

import wx
import pexpect
import subprocess

# begin wxGlade: extracode
# end wxGlade



class Frame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Frame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_3 = wx.StaticText(self, -1, "Gmail:")
        self.text_ctrl_3 = wx.TextCtrl(self, -1, "")
        self.label_4 = wx.StaticText(self, -1, "Password:")
        self.text_ctrl_4 = wx.TextCtrl(self, -1, "", style=wx.TE_PASSWORD)
        self.label_5 = wx.StaticText(self, -1, "Directory:")
        self.text_ctrl_5 = wx.TextCtrl(self, -1, "")
        self.button_6 = wx.Button(self, -1, "Browse")
        self.button_6.Bind(wx.EVT_BUTTON, self.OnBrowse)
        self.button_8 = wx.Button(self, -1, "Close")
        self.button_8.Bind(wx.EVT_BUTTON, self.OnClose)
        self.button_9 = wx.Button(self, -1, "Mount")
        self.button_9.Bind(wx.EVT_BUTTON, self.OnMount)
        self.button_10 = wx.Button(self, -1, "Unmount")
        self.button_10.Bind(wx.EVT_BUTTON, self.OnUnmount)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        
    def OnClose(self, event):
        self.Destroy()
            
    def OnBrowse(self, event):
        dirdlg = wx.DirDialog(self, "Choose the mount directory:")
        if dirdlg.ShowModal() == wx.ID_OK:
            self.text_ctrl_5.ChangeValue("%s" % dirdlg.GetPath())
        dirdlg.Destroy()
        
    def OnMount(self, event):
        account = self.text_ctrl_3.GetValue()
        password = self.text_ctrl_4.GetValue()
        directory = self.text_ctrl_5.GetValue()
        mount_child = pexpect.spawn ('gmount %s %s' % (directory, account))
        mount_child.expect('Password:')
        mount_child.sendline('%s' % password)
        
    def OnUnmount(self, event):
        directory = self.text_ctrl_5.GetValue()
        subprocess.call(['gumount', '%s' % directory])

    def __set_properties(self):
        # begin wxGlade: Frame.__set_properties
        self.SetTitle("Mount Google Docs")
        self.text_ctrl_3.SetMinSize((200, 21))
        self.text_ctrl_4.SetMinSize((200, 21))
        self.text_ctrl_5.SetMinSize((200, 21))
        self.button_6.SetMinSize((67, 34))
        self.button_8.SetMinSize((67, 34))
        self.button_9.SetMinSize((67, 34))
        self.button_10.SetMinSize((67, 34))
        self.button_10.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Frame.__do_layout
        grid_sizer_2 = wx.FlexGridSizer(4, 2, 6, 6)
        grid_sizer_3 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(self.label_3, 0, 0, 0)
        grid_sizer_2.Add(self.text_ctrl_3, 0, 0, 0)
        grid_sizer_2.Add(self.label_4, 0, 0, 0)
        grid_sizer_2.Add(self.text_ctrl_4, 0, 0, 0)
        grid_sizer_2.Add(self.label_5, 0, 0, 0)
        grid_sizer_2.Add(self.text_ctrl_5, 0, 0, 0)
        grid_sizer_2.Add(self.button_6, 0, 0, 0)
        grid_sizer_3.Add(self.button_8, 0, 0, 0)
        grid_sizer_3.Add(self.button_9, 0, 0, 0)
        grid_sizer_3.Add(self.button_10, 0, 0, 0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_2)
        grid_sizer_2.Fit(self)
        self.Layout()
        # end wxGlade

# end of class Frame


class GDocsGUI(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frame_1 = Frame(None, -1, "")
        self.SetTopWindow(frame_1)
        frame_1.Show()
        return 1

# end of class GDocsGUI

if __name__ == "__main__":
    gdocsgui = GDocsGUI(0)
    gdocsgui.MainLoop()
